app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/

Route::group(['middleware' => ['web']], function () {
	Route::get('teacherdashboard/register','TeacherController@preregister');
	Route::post('teacherdashboard/register','TeacherController@postregister');	
	Route::get('teacherdashboard/logout','TeacherController@logout');			
	Route::get('admindashboard/logout','AdminController@logout');	
	Route::group(['middleware' =>'guest'], function () {
		Route::get('/','MainSiteController@index');
		Route::get('home','MainSiteController@index');
		Route::get('aboutus','MainSiteController@aboutus');
		Route::get('gallery','MainSiteController@gallery');
		Route::get('contactus','MainSiteController@precontactus');
		Route::get('courses','MainSiteController@courses');
		Route::get('courses/{id}','MainSiteController@coursedetails');
		Route::get('teacher','MainSiteController@teacher');
		Route::get('admin','AdminController@admin');			
		Route::post('admin','AdminController@login');					
		Route::resource('message','MessageController',['only' => ['store']]);			
		Route::post('teacher','TeacherController@login');
	});
	Route::group(['middleware' =>'auth'], function () {
		Route::group(['middleware' =>'teacher'], function () {
				Route::get('admindashboard/filelist','AdminController@filelist');			
				Route::get('admindashboard/download/{id}','TeacherFileController@download');		
				Route::get('teacherdashboard/download/{id}','TeacherFileController@download');
				Route::post('admindashboard/filelist','TeacherFileController@search');	
				Route::group(['middleware' =>'HrAndSpc'], function () {
					Route::get('admindashboard/whitelist','AdminController@whitelist');					
					Route::get('admindashboard/courses','AdminController@courses');					
					Route::get('admindashboard/index','AdminController@index');
					Route::post('admindashboard/index','MessageController@search');						
					Route::post('admindashboard/whitelist','WhiteListController@search');
				});								
				Route::resource('admindashboard','AdminController');	
				Route::resource('whitelist','WhiteListController');		
				Route::resource('course','CourseController');	
		});

		
							
		Route::group(['middleware' =>'admin'], function () {
			Route::resource('teacherdashboard','TeacherController');							
			Route::resource('teacherfile','TeacherFileController');			
		});
		Route::resource('teacherfile','TeacherFileController',['except' => ['store,create']]);					
		Route::resource('message','MessageController',['only' => ['destroy','show']]);					
	});				
});

resources/views/admindashboard/courses.blade.php
@extends('templates.admindashboard')
@section('nav')
	<ul>
		@if($user['type']==1)
			<li><a href="{{url('admindashboard')}}">Messages</a></li>
			<li><a href="{{url('admindashboard/filelist')}}">Files</a></li>						
			<li class="active"><a href="{{url('admindashboard/courses')}}">Courses</a></li>														
			<li><a href="{{url('admindashboard/whitelist')}}">WhiteList</a></li>						
		@else
			<li class="active"><a href="{{url('admindashboard/filelist')}}">Files</a></li>								
		@endif
	</ul>
@endsection
@section('content')
	<div class="two columns">
	  	<form id="frmadd" action="{{route('course.create')}}">
			<button class="button-primary" type="submit" id="btnadd"  name="btnadd"><i class="fa fa-plus fa-2x"></i></button>
		</form>					      																			
	</div>
	<table class="u-full-width">
	  <thead>
	    <tr>
	      <th>Date</th>					    
	      <th>Name</th>
	      <th>Navigation</th>					      
	    </tr>
	  </thead>
	  <tbody>
	  	@foreach($courses as $course)
		    <tr>
		      <td><p>{{date('m-d-Y H:i:s',strtotime($course['created_at']))}}</p></td>						    
		      <td><p>{{$course['name']}}</p></td>
		      <td>
			      <div class="row">
      				   <div class="one-half column">
					      	<form method="GET" id="frmedit" action="{{route('course.edit',['id'=>$course['id']])}}">					      			
					      			<button class="button-primary" type="submit" id="btnedit"  name="btnedit"><i class="fa fa-pencil-square-o fa-2x"></i></button>
			      			</form>			      					
			      		</div>							      						      
		      			<div class="one-half column">
		      				<form method="POST" id="frmdelete" action="{{route('course.destroy',['id'=>$course['id']])}}">
				      			{{csrf_field()}}
                                <input name="_method" type="hidden" value="DELETE">							      			
				      			<button class="button-danger" type="submit" id="btndelete"  name="btndelete" value="Download"><i class="fa fa-times fa-2x"></i></button>
				      		</form>
		      			</div>			      									      	
			      	
			      </div>
		      </td>						      
		    </tr>					  	
	  	@endforeach
	  </tbody>
	</table>	
	{!! $courses->render() !!}									
@endsection

resources/views/admindashboard/filelist.blade.php
@extends('templates.admindashboard')
@section('nav')
	<ul>
		@if($user['type']==1)
			<li><a href="{{url('admindashboard')}}">Messages</a></li>
			<li class="active"><a href="{{url('admindashboard/filelist')}}">Files</a></li>						
			<li><a href="{{url('admindashboard/courses')}}">Courses</a></li>														
			<li><a href="{{url('admindashboard/whitelist')}}">WhiteList</a></li>						
		@else
			<li class="active"><a href="{{url('admindashboard/filelist')}}">Files</a></li>								
		@endif
	</ul>
@endsection
@section('content')
	<div class="twelve columns">
	  	<form method="POST" id="frmsearch" action="{{url('admindashboard/filelist')}}">
			{{csrf_field()}}
	  		<div class="row">
				<div class="nine columns">
			  		<input id="name" name="name" type="text" placeholder="Teacher Name">
				</div>	  			
				<div class="three columns">
					<button class="button-primary" type="submit" id="btnsearch"  name="btnserach"><i class="fa fa-search fa-2x"></i></button>
				</div>	  											
	  		</div>

		</form>					      																			
	</div>
	<table class="u-full-width">
	  <thead>
	    <tr>
	      <th>Date</th>
	      <th>Teacher</th>					      
	      <th>Name</th>
	      <th>Type</th>
	      <th>SendTo</th>	      
	      <th colspan="3">Navigation</th>
	    </tr>
	  </thead>
	  <tbody>
	  	@foreach($teacherfiles as $file)
		    <tr>
		      <td><p>{{date('m-d-Y H:i:s',strtotime($file['created_at']))}}</p></td>
		      <td><p>{{$file->teacher['firstname']}} {{$file->teacher['lastname']}}</p></td>
		      <td><p>{{$file['name']}}</p></td>
		      <td><p>{{strtoupper($file['type'])}}</p></td>
		      <td><p>{{$file['usertype']['name']}}</p></td>
		      <td>
		      	<form method="GET" id="frmedit" action="{{route('teacherfile.edit',['id'=>$file['id']])}}">  			
	      			<button class="button-primary" type="submit" id="btnedit"  name="btnedit"><i class="fa fa-pencil-square-o fa-fw fa-2x"></i></button>
  				</form>
		      </td>
		      <td>
		      	<form id="frmedownload" action="download/{{$file['id']}}">
	      			{{csrf_field()}}	      			
	      			<button class="button-primary" type="submit" id="btndownload"  name="btndownload" value="Download"><i class="fa fa-cloud fa-fw fa-2x"></i></button>
  				</form>				      					
		      </td>
		      <td>
  				<form method="POST" id="frmdelete" action="{{route('teacherfile.destroy',['id'=>$file['id']])}}">
	      			{{csrf_field()}}
                    <input name="_method" type="hidden" value="DELETE">      			
	      			<button class="button-danger" type="submit" id="btndelete"  name="btndelete" value="Download"><i class="fa fa-fw fa-times fa-2x"></i></button>
	      		</form>
		      </td>		      		      
		    </tr>					  	
	  	@endforeach
	  </tbody>
	</table>				
	<p>Total: {{$teacherfiles->count()}}</p>
	{!! $teacherfiles->render() !!}									
@endsection

resources/views/admindashboard/index.blade.php
@extends('templates.admindashboard')
@section('nav')
	<ul>
		@if($user['type']==1)
			<li class="active"><a href="{{url('admindashboard')}}">Messages</a></li>
			<li><a href="{{url('admindashboard/filelist')}}">Files</a></li>						
			<li><a href="{{url('admindashboard/courses')}}">Courses</a></li>														
			<li><a href="{{url('admindashboard/whitelist')}}">WhiteList</a></li>						
		@else
			<li class="active"><a href="{{url('admindashboard/filelist')}}">Files</a></li>								
		@endif
						
	</ul>
@endsection
@section('content')
	<div class="twelve columns">
	  	<form method="POST" id="frmsearch" action="{{url('admindashboard/index')}}">
			{{csrf_field()}}
	  		<div class="row">
				<div class="nine columns">
			  		<input id="email" name="email" type="text" placeholder="Email">
				</div>	  			
				<div class="three columns">
					<button class="button-primary" type="submit" id="btnsearch"  name="btnserach"><i class="fa fa-search fa-2x"></i></button>
				</div>	  											
	  		</div>

		</form>					      																			
	</div>
	<table class="u-full-width">
	  <thead>
	    <tr>
	      <th>Date</th>
	      <th>Email</th>
	      <th>Number</th>
	      <th>Navigation</th>					      
	    </tr>
	  </thead>
	  <tbody>
	  	@foreach($messages as $message)
		    <tr>
		      <td><p>{{date('m-d-Y H:i:s',strtotime($message['created_at']))}}</p></td>
		      <td><p>{{$message['email']}}</p></td>
		      <td>
		      <p>{{$message['contactnumber']}}</p></td>						      
		      <td>
	      		<div class="row">
	      			<div class="one-half column">
	      				<form method="get" id="frmdelete" action="{{route('message.show',['id'=>$message['id']])}}">
			      			<button class="button-primary" type="submit" id="btnshow"  name="btnshow"><i class="fa fa-eye fa-2x"></i></button>
			      		</form>
	      			</div>			      			
	      			<div class="one-half column">
	      				<form method="POST" id="frmdelete" action="{{route('message.destroy',['id'=>$message['id']])}}">
			      			{{csrf_field()}}
	                        <input name="_method" type="hidden" value="DELETE">							      			
			      			<button class="button-danger" type="submit" id="btndelete"  name="btndelete"><i class="fa fa-times fa-2x"></i></button>
			      		</form>
	      			</div>			      			
	      		</div>						      	
		      </td>
		    </tr>					  	
	  	@endforeach
	  </tbody>
	</table>	
	{!! $messages->render() !!}									
@endsection

resources/views/admindashboard/whitelist.blade.php
@extends('templates.admindashboard')
@section('nav')
	<ul>
		@if($user['type']==1)
			<li><a href="{{url('admindashboard')}}">Messages</a></li>
			<li><a href="{{url('admindashboard/filelist')}}">Files</a></li>						
			<li><a href="{{url('admindashboard/courses')}}">Courses</a></li>														
			<li class="active"><a href="{{url('admindashboard/whitelist')}}">WhiteList</a></li>						
		@else
			<li class="active"><a href="{{url('admindashboard/filelist')}}">Files</a></li>								
		@endif						
	</ul>
@endsection
@section('content')
	<div class="two columns">
	  	<form id="frmadd" action="{{route('whitelist.create')}}">
			<button class="button-primary" type="submit" id="btnadd"  name="btnadd"><i class="fa fa-plus fa-2x"></i></button>
		</form>					      																			
	</div>
	<div class="twelve columns">
	  	<form method="POST" id="frmsearch" action="{{url('admindashboard/whitelist')}}">
			{{csrf_field()}}
	  		<div class="row">
				<div class="nine columns">
			  		<input id="email" name="email" type="text" placeholder="Email">
				</div>	  			
				<div class="three columns">
					<button class="button-primary" type="submit" id="btnsearch"  name="btnserach"><i class="fa fa-search fa-2x"></i></button>
				</div>	  											
	  		</div>

		</form>					      																			
	</div>	
	<table class="u-full-width">
	  <thead>
	    <tr>
	      <th>Date</th>					    
	      <th>Email</th>
	      <th>Type</th>					      
	      <th>Navigation</th>					      
	    </tr>
	  </thead>
	  <tbody>
	  	@foreach($whitelists as $whitelist)
		    <tr>
		      <td><p>{{date('m-d-Y H:i:s',strtotime($whitelist['created_at']))}}</p></td>						    
		      <td><p>{{$whitelist['email']}}</p></td>
		      <td><p>{{$usertypes->find($whitelist->user['type'])['name']}}</p></td>
		      <td>
			      <div class="row">
      				   <div class="one-half column">
					      	<form method="GET" id="frmedit" action="{{route('whitelist.edit',['id'=>$whitelist['id']])}}">					      			
					      			<button class="button-primary" type="submit" id="btnedit"  name="btnedit"><i class="fa fa-pencil-square-o fa-2x"></i></button>
			      			</form>			      					
			      		</div>							      						      
		      			<div class="one-half column">
		      				<form method="POST" id="frmdelete" action="{{route('whitelist.destroy',['id'=>$whitelist['id']])}}">
				      			{{csrf_field()}}
                                <input name="_method" type="hidden" value="DELETE">							      			
				      			<button class="button-danger" type="submit" id="btndelete"  name="btndelete" value="Download"><i class="fa fa-times fa-2x"></i></button>
				      		</form>
		      			</div>			      									      			      	
			      </div>
		      </td>						      
		    </tr>					  	
	  	@endforeach
	  </tbody>
	</table>	
	{!! $whitelists->render() !!}									
@endsection