app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/

Route::group(['middleware' => ['web']], function () {
	Route::get('teacherdashboard/register','TeacherController@preregister');
	Route::post('teacherdashboard/register','TeacherController@postregister');	
	Route::get('teacherdashboard/logout','TeacherController@logout');			
	Route::get('admindashboard/logout','AdminController@logout');	
	Route::group(['middleware' =>'guest'], function () {
		Route::get('/','MainSiteController@index');
		Route::get('home','MainSiteController@index');
		Route::get('aboutus','MainSiteController@aboutus');
		Route::get('gallery','MainSiteController@gallery');
		Route::get('contactus','MainSiteController@precontactus');
		Route::get('courses','MainSiteController@courses');
		Route::get('courses/{id}','MainSiteController@coursedetails');
		Route::get('teacher','MainSiteController@teacher');
		Route::get('admin','AdminController@admin');			
		Route::post('admin','AdminController@login');					
		Route::resource('message','MessageController',['only' => ['store']]);			
		Route::post('teacher','TeacherController@login');
	});
	Route::group(['middleware' =>'auth'], function () {
		Route::group(['middleware' =>'teacher'], function () {
				Route::get('admindashboard/filelist','AdminController@filelist');			
				Route::get('admindashboard/download/{id}','TeacherFileController@download');		
				Route::get('teacherdashboard/download/{id}','TeacherFileController@download');
				Route::post('admindashboard/filelist','TeacherFileController@search');	
				Route::group(['middleware' =>'HrAndSpc'], function () {
					Route::get('admindashboard/whitelist','AdminController@whitelist');					
					Route::get('admindashboard/courses','AdminController@courses');					
					Route::get('admindashboard/index','AdminController@index');
					Route::post('admindashboard/index','MessageController@search');						
					Route::post('admindashboard/whitelist','WhiteListController@search');
				});								
				Route::resource('admindashboard','AdminController');	
				Route::resource('whitelist','WhiteListController');		
				Route::resource('course','CourseController');	
		});

		
							
		Route::group(['middleware' =>'admin'], function () {
			Route::resource('teacherdashboard','TeacherController');							
			Route::resource('teacherfile','TeacherFileController');			
		});
		Route::resource('teacherfile','TeacherFileController',['except' => ['store,create']]);					
		Route::resource('message','MessageController',['only' => ['destroy','show']]);					
	});				
});

app/TeacherFile.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
class TeacherFile extends Model
{
    use SoftDeletes;
    protected $dates = ['deleted_at'];	
	protected $table='teacher_files';
	public function teacher(){
        return $this->belongsTo('App\Teacher','teacher_id');
	}
	public function UserType(){
    	return $this->hasOne('App\UserType','id','sendTo');
	}
}

app/Http/Controllers/TeacherFileController.php
<?php

namespace App\Http\Controllers;

use Auth;
use App;
use Storage;

use Illuminate\Http\Request;

use App\TeacherFile;
use App\Teacher;
use App\UserType;

use App\Http\Requests\TeacherFileRequests;
use App\Http\Controllers\Controller;

class TeacherFileController extends Controller
{
	public function create(Request $request){
		$referer=$request->headers->get('referer');
		if(strpos($referer,'=')===false){
			$request->session()->put('referer',$referer);			    					
		}
	    $usertypes=UserType::whereIn('name',['User/Human Resource','User/School Program Coordinator'])->get();	   		
		return view('teacherfile.create',compact('usertypes'));
	}	
	public function edit(Request $request,$id){	
		$referer=$request->headers->get('referer');
		if(strpos($referer,'=')===false){
			$request->session()->put('referer',$referer);			    					
		}
	    $usertypes=UserType::whereIn('name',['User/Human Resource','User/School Program Coordinator'])->get();		
		$teacherfile=TeacherFile::where('id','=',$id)->first();
		return view('teacherfile.edit')->with(compact('teacherfile','usertypes'));
	}
	public function update(TeacherFileRequests $request,$id){
		$referer=session('referer');
		$sendTo=$request['sendto'];
		$description=$request['description'];
		$teacherfile=TeacherFile::where('id','=',$id)->first();
		//$teacherfile->name=$name;
		$teacherfile->description=$description;	
		$teacherfile->sendTo=$sendTo;			
		$teacherfile->update();
		$request->session()->flash('status', 'File updated.');			    				
		$request->session()->forget('referer');		
		if(strpos($referer,'admindashboard')!==false){
			return redirect('admindashboard/filelist');				
		}		
		return redirect('teacherdashboard');
	}
	public function store(TeacherFileRequests $request){
		$sendTo=$request['sendto'];
	    $file=$request->file('file');
		$origName=explode('.',$file->getClientOriginalName());
		$name=trim($origName[count($origName)-2]);
		$description=$request['description'];
		$extension=$file->getClientOriginalExtension();
		$user=\Auth::user();

	    $filecontents = file_get_contents($file->getRealPath());	
	    //$filepath=$user->id.'/files/'.$filename;
	    $fileAndNameArr=$this->getFilePathAndName($user->id,$name,$extension);
	    Storage::disk('local')->put($fileAndNameArr[0], $filecontents);	         		

		$teacherfile=new TeacherFile;
		$teacherfile->teacher_id=$user->teacher['id'];
		$teacherfile->filepath=$fileAndNameArr[0];
		$teacherfile->name=$fileAndNameArr[1];
		$teacherfile->description=$description;
		$teacherfile->type=$extension;
		$teacherfile->sendTo=$sendTo;
		$teacherfile->save();
		$request->session()->flash('status', 'Uploaded.');			    		
		$request->session()->forget('referer');		
		return redirect('teacherdashboard');
	}
	public function destroy(Request $request,$id){	
		$referer=$request->headers->get('referer');
		$teacherfile=TeacherFile::where('id','=',$id)->first();	
		if(strpos($referer,'admindashboard')!==false){
			\DB::transaction(function() use ($teacherfile,$request) {
				// Storage::disk('local')->delete($teacherfile['filepath']);
				$teacherfile->deletedByAdmin=true;	
				$teacherfile->update();
				$request->session()->flash('status', 'File deleted.');			    		
			});		
			return redirect('admindashboard/filelist');				
		}		
		\DB::transaction(function() use ($teacherfile,$request) {
			Storage::disk('local')->delete($teacherfile['filepath']);
			$teacherfile->delete();	
			$request->session()->flash('status', 'File deleted.');			    		
		});				
		return redirect('teacherdashboard');	
	}
	public function download($id){
		$teacherfile=TeacherFile::find($id);		   	
		$filepath=$teacherfile['filepath'];
	    return response()->download(storage_path('app').'/'.$filepath);   
	} 
	public function search(Request $request){
		$user=Auth::user();
		$teacherfiles=TeacherFile::whereIn('teacher_id',
	 	function($query) use ($request){
    		$query->select('id')->from(with(new Teacher)->getTable())
    		->where('lastname','LIKE', '%'.$request['name'].'%')
    		->orWhere('firstname','LIKE', '%'.$request['name'].'%')
    		->orWhere('middlename','LIKE', '%'.$request['name'].'%'); 
    	});
    	if($user['type']!=1){
		 $teacherfiles=$teacherfiles->where('sendTo','=',$user['type']);    		
    	}
    	$teacherfiles=$teacherfiles->paginate(10);
		return view('admindashboard.filelist')->with(compact('teacherfiles','user'));
	}   
	private function getFilePathAndName($id,$origName,$extension){
		$i=1;
		$name=$origName;
		while(true){
			$filename=$name.'.'.$extension;
			$filepath=$id.'/files/'.$filename;			
			$exist=Storage::disk('local')->has($filepath);
			if($exist){
				$name=$origName.'['.$i.']';
			}			
			else{
				return array($filepath,$name);
			}
			$i+=1;
		}
	}	
}

resources/views/teacherfile/create.blade.php
@extends('templates.dashboard')
@section('content')
<div class="twelve columns teacherfile">
	<div class="row">
		<div class="ten columns offset-by-one">
			<form method="POST" id="frmcreate" action="{{route('teacherfile.store')}}" enctype="multipart/form-data">
				{{csrf_field()}}
				<label for="sendto">Send To</label>
				<select id="sendto" name="sendto">
					@foreach($usertypes as $usertype)
						<option value="{{$usertype['id']}}">{{$usertype['name']}}</option>
					@endforeach
				</select>
				<p class="error">{{ $errors->first('type') }}</p>						
				<label for="description">Description</label>				
				<textarea id="description" name="description">{{old('name')}}</textarea>
				<p class="error">{{ $errors->first('description') }}</p>																		
				<label for="file">File</label>
				<input id="file" name="file" type="file" value="{{old('file')}}">		
				<p class="error">{{ $errors->first('file') }}</p>											
				<button class="button-primary" type="submit"><i class="fa fa-cloud-upload fa-2x"></i></button>										
				<a class="anchorblue animsition-link" href="{{ session('referer') }}">Back</a>
			</form>
		</div>
	</div>
</div>
@endsection

resources/views/teacherfile/edit.blade.php
@extends('templates.dashboard')
@section('content')
<div class="twelve columns teacherfile">
	<div class="row">
		<div class="ten columns offset-by-one">
			<form method="POST" id="frmedit" action="{{route('teacherfile.update',['id'=>$teacherfile['id']])}}" enctype="multipart/form-data">
				{{csrf_field()}}
		        <input name="_method" type="hidden" value="PATCH">							      			
				<label for="sendto">Send To</label>		
				<select id="sendto" name="sendto">
					@foreach($usertypes as $usertype)
						@if($teacherfile['sendTo']==$usertype['id'])
							<option value="{{$usertype['id']}}" selected="">{{$usertype['name']}}</option>
						@else
							<option value="{{$usertype['id']}}">{{$usertype['name']}}</option>
						@endif
					@endforeach
				</select>
				<p class="error">{{ $errors->first('type') }}</p>				
				<label for="description">Description</label>				
				<textarea id="description" name="description"s>{{$teacherfile['description']}}</textarea>
				<p class="error">{{ $errors->first('description') }}</p>																		
				<button class="button-primary" type="submit"><i class="fa fa-pencil-square-o fa-2x"></i></button>										
				<a class="anchorblue" href="{{ session('referer') }}">Back</a>
			</form>
		</div>
	</div>
</div>
@endsection