app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/

Route::group(['middleware' => ['web']], function () {
	Route::get('teacherdashboard/register','TeacherController@preregister');
	Route::post('teacherdashboard/register','TeacherController@postregister');	
	Route::get('teacherdashboard/logout','TeacherController@logout');			
	Route::get('admindashboard/logout','AdminController@logout');	
	Route::group(['middleware' =>'guest'], function () {
		Route::get('/','MainSiteController@index');
		Route::get('home','MainSiteController@index');
		Route::get('aboutus','MainSiteController@aboutus');
		Route::get('gallery','MainSiteController@gallery');
		Route::get('contactus','MainSiteController@precontactus');
		Route::get('courses','MainSiteController@courses');
		Route::get('courses/{id}','MainSiteController@coursedetails');
		Route::get('teacher','MainSiteController@teacher');
		Route::get('admin','AdminController@admin');			
		Route::post('admin','AdminController@login');					
		Route::resource('message','MessageController',['only' => ['store']]);			
		Route::post('teacher','TeacherController@login');
	});
	Route::group(['middleware' =>'auth'], function () {
		Route::group(['middleware' =>'teacher'], function () {
				Route::get('admindashboard/filelist','AdminController@filelist');			
				Route::get('admindashboard/download/{id}','TeacherFileController@download');		
				Route::get('teacherdashboard/download/{id}','TeacherFileController@download');
				Route::post('admindashboard/filelist','TeacherFileController@search');	
				Route::group(['middleware' =>'HrAndSpc'], function () {
					Route::get('admindashboard/whitelist','AdminController@whitelist');					
					Route::get('admindashboard/courses','AdminController@courses');					
					Route::get('admindashboard/index','AdminController@index');
					Route::post('admindashboard/index','MessageController@search');						
					Route::post('admindashboard/whitelist','WhiteListController@search');
				});								
				Route::resource('admindashboard','AdminController');	
				Route::resource('whitelist','WhiteListController');		
				Route::resource('course','CourseController');	
		});

		
							
		Route::group(['middleware' =>'admin'], function () {
			Route::resource('teacherdashboard','TeacherController');							
			Route::resource('teacherfile','TeacherFileController');			
		});
		Route::resource('teacherfile','TeacherFileController',['except' => ['store,create']]);					
		Route::resource('message','MessageController',['only' => ['destroy','show']]);					
	});				
});

resources/views/teacherdashboard/edit.blade.php
@extends('templates.dashboard')
@section('content')
<div class="twelve columns teacherdashboard">
	<div class="row">
		<div class="ten columns offset-by-one">
			<form method="POST" id="frmedit" action="{{route('teacherdashboard.update',['id'=>$teacher['id']])}}" enctype="multipart/form-data">
				{{csrf_field()}}
		        <input name="_method" type="hidden" value="PATCH">							      			
				<label for="firstname">First Name:</label>
				<input type="text" id="firstname" name="firstname" value="{{$teacher['firstname']}}">								
	        	<p class="error">{{ $errors->first('firstname') }}</p>								
				<label for="middlename">Middle Name:</label>
				<input type="text" id="middlename" name="middlename" value="{{$teacher['middlename']}}">										
				<p class="error">{{ $errors->first('middlename') }}</p>
				<label for="lastname">Last Name:</label>
				<input type="text" id="lastname" name="lastname" value="{{$teacher['lastname']}}">						
				<p class="error">{{ $errors->first('lastname') }}</p>								
				<label for="address">Address:</label>
				<textarea id="address" name="address">{{$teacher['address']}}</textarea>					    		
				<p class="error">{{ $errors->first('address') }}</p>								
				<label for="password">Password:</label>		
				<input type="password" id="password" name="password" placeholder="Leave this blank if you dont want to change">								
				<p class="error">{{ $errors->first('password') }}</p>								
				<label for="password_confirmation">Confirm Password:</label>		
				<input type="password" id="password_confirmation" name="password_confirmation" placeholder="Leave this blank if you dont want to change">						    		
				<p class="error">{{ $errors->first('password_confirmation') }}</p>								
				<label for="profilepic">Profile Picture:</label>		
				<input type="file" id="profilepic" name="profilepic">								    	
				<p class="error">{{ $errors->first('profilepic') }}</p>								
				<button class="button-primary" type="submit"><i class="fa fa-pencil-square-o fa-2x"></i></button>										
				<a class="anchorblue" href="{{ session('referer') }}">Back</a>
			</form>
		</div>
	</div>
</div>
@endsection

resources/views/teacherdashboard/index.blade.php
@extends('templates.dashboard')
@section('content')
<div class="twelve columns teacherdashboard">
	<div class="row">
		<div class="eight columns filelist">
			<div class="row">
				<div class="twelve column">		
					<div class="three columns">
				      	<form id="frmadd" action="{{route('teacherfile.create')}}">
			      			<button class="button-primary" type="submit" id="btnadd"  name="btnadd"><i class="fa fa-plus fa-2x"></i></button>
		  				</form>					      																			
					</div>

					<table class="u-full-width">
					  <thead>
					    <tr>
					      <th>Date</th>
					      <th>Name</th>
					      <th>Type</th>
					      <th colspan="3">Navigation</th>
					    </tr>
					  </thead>
					  <tbody>
					  	@foreach(\Auth::user()->teacher->files()->orderBy('created_at', 'desc')->paginate(10) as $file)
						    <tr>
						      <td>{{date('m-d-Y H:i:s',strtotime($file['created_at']))}}</td>
						      <td>{{$file['name']}}</td>
						      <td>{{strtoupper($file['type'])}}</td>
						      <td>
							      	<form method="GET" id="frmedit" action="{{route('teacherfile.edit',['id'=>$file['id']])}}">					      			
						      			<button class="button-primary" type="submit" id="btnedit"  name="btnedit"><i class="fa fa-pencil-square-o fa-2x"></i></button>
				      				</form>						      	
						      </td>
						      <td>
							      	<form id="frmedownload" action="teacherdashboard/download/{{$file['id']}}">	
						      			<button class="button-primary" type="submit" id="btndownload"  name="btndownload" value="Download"><i class="fa fa-cloud fa-2x"></i></button>
				      				</form>		      	
						      </td>
						      <td>
					      				<form method="POST" id="frmdelete" action="{{route('teacherfile.destroy',['id'=>$file['id']])}}">
							      			{{csrf_field()}}
	                                        <input name="_method" type="hidden" value="DELETE">							      			
							      			<button class="button-danger" type="submit" id="btndelete"  name="btndelete" value="Download"><i class="fa fa-times fa-2x"></i></button>
							      		</form>						      	
						      </td>
						    </tr>					  	
					  	@endforeach
					  </tbody>
					</table>	
					<p>Total: {{Auth::user()->teacher->files()->count()}}</p>					
					{!! Auth::user()->teacher->files()->orderBy('created_at', 'desc')->paginate(10)->render() !!}
				</div>
			</div>

		</div>		
		<div class="four columns profile">
			<div class="row">
				<div class="twelve column">
					<img class="u-max-full-width" id="profilepic" name="profilepic" src="{{\Auth::user()->teacher['profileurl']}}">
					<p>ID NO: {{\Auth::user()->teacher['id']}}</p>										
					<p>FIRST NAME: {{ucfirst(\Auth::user()->teacher['firstname'])}}</p>
					<p>MIDDLE NAME: {{ucfirst(\Auth::user()->teacher['middlename'])}}</p>					
					<p>LAST NAME: {{ucfirst(\Auth::user()->teacher['lastname'])}}</p>					
					<p>ADDRESS: {{ucfirst(\Auth::user()->teacher['address'])}}</p>
				</div>				
			</div>
			<div class="row">
				<div class="one-half column">
			      	<form method="GET" id="frmedit" action="{{route('teacherdashboard.edit',['id'=>\Auth::user()->teacher['id']])}}">					      			
		      			<button class="button-primary" type="submit" id="btnedit"  name="btnedit"><i class="fa fa-pencil-square-o fa-2x"></i></button>
      				</form>
				</div>
				<div class="one-half column">
					<form method="GET" id="frmlogout" action="{{url('teacherdashboard/logout')}}">
			  			<button class="button-danger" type="submit" id="btnlogout" name="btnlogout"><i class="fa fa-sign-out fa-2x"></i></button>			      					      				
					</form>															
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/teacherdashboard/register.blade.php
@extends('templates.main')
@section('header')
<div id="nav" class="twelve columns">
	<ul>
		<li>
				<a class="animsition-link" href="{{url('home')}}">Home</a>
		</li>
		<li>
				<a class="animsition-link" href="{{url('aboutus')}}">About</a>
		</li>
		<li>
				<a class="animsition-link" href="{{url('gallery')}}">Gallery</a>
		</li>
		<li>
				<a class="animsition-link" href="{{url('courses')}}">Course Offered</a>
		</li>
		<li>
				<a>Storage</a>
 		        <ul>
            		<li><a href="{{url('admin')}}">Administrator</a></li>
            		<li class="active"><a href="{{url('teacher')}}">Teacher</a></li>
          		</ul>						
		</li>
		<li>
				<a class="animsition-link" href="{{url('contactus')}}">Contacts</a>
		</li>																				
	</ul>				
</div>	
@endsection
@section('content')
<div class="twelve columns teacherdashboard">
	<div class="row">
		<div class="ten columns offset-by-one">	
			<form method="POST" action="{{url('teacherdashboard/register')}}" enctype="multipart/form-data">
				{{ csrf_field() }}
				<label for="firstname">First Name:</label>
				<input type="text" id="firstname" name="firstname" value="{{old('firstname')}}">								
	        	<p class="error">{{ $errors->first('firstname') }}</p>								
				<label for="middlename">Middle Name:</label>
				<input type="text" id="middlename" name="middlename" value="{{old('middlename')}}">										
				<p class="error">{{ $errors->first('middlename') }}</p>
				<label for="lastname">Last Name:</label>
				<input type="text" id="lastname" name="lastname" value="{{old('lastname')}}">						
				<p class="error">{{ $errors->first('lastname') }}</p>								
				<label for="address">Address:</label>
				<textarea id="address" name="address">{{old('address')}}</textarea>					    		
				<p class="error">{{ $errors->first('address') }}</p>								
				<label for="email">Email:</label>
				<input type="email" id="email" name="email" value="{{old('email')}}">
				<p class="error">{{ $errors->first('email') }}</p>
				<label for="password">Password:</label>		
				<input type="password" id="password" name="password" value="{{old('password')}}">								
				<p class="error">{{ $errors->first('password') }}</p>								
				<label for="password_confirmation">Confirm Password:</label>		
				<input type="password" id="password_confirmation" name="password_confirmation" value="{{old('password_confirmation')}}">						    		
				<p class="error">{{ $errors->first('password_confirmation') }}</p>								
				<label for="profilepic">Profile Picture:</label>		
				<input type="file" id="profilepic" name="profilepic" value="{{old('profilepic')}}">								    	
				<p class="error">{{ $errors->first('profilepic') }}</p>								
				<button class="button-primary" type="submit" id="btnsubmit" name="btnsubmit">Register</button>	
				<a class="anchorblue animsition-link" href="{{ session('referer') }}">Back</a>
			</form>
		</div>
	</div>		
</div>
@endsection