app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/

Route::group(['middleware' => ['web']], function () {
	Route::get('teacherdashboard/register','TeacherController@preregister');
	Route::post('teacherdashboard/register','TeacherController@postregister');	
	Route::get('teacherdashboard/logout','TeacherController@logout');			
	Route::get('admindashboard/logout','AdminController@logout');	
	Route::group(['middleware' =>'guest'], function () {
		Route::get('/','MainSiteController@index');
		Route::get('home','MainSiteController@index');
		Route::get('aboutus','MainSiteController@aboutus');
		Route::get('gallery','MainSiteController@gallery');
		Route::get('contactus','MainSiteController@precontactus');
		Route::get('courses','MainSiteController@courses');
		Route::get('courses/{id}','MainSiteController@coursedetails');
		Route::get('teacher','MainSiteController@teacher');
		Route::get('admin','AdminController@admin');			
		Route::post('admin','AdminController@login');					
		Route::resource('message','MessageController',['only' => ['store']]);			
		Route::post('teacher','TeacherController@login');
	});
	Route::group(['middleware' =>'auth'], function () {
		Route::group(['middleware' =>'teacher'], function () {
				Route::get('admindashboard/filelist','AdminController@filelist');			
				Route::get('admindashboard/download/{id}','TeacherFileController@download');		
				Route::get('teacherdashboard/download/{id}','TeacherFileController@download');
				Route::post('admindashboard/filelist','TeacherFileController@search');	
				Route::group(['middleware' =>'HrAndSpc'], function () {
					Route::get('admindashboard/whitelist','AdminController@whitelist');					
					Route::get('admindashboard/courses','AdminController@courses');					
					Route::get('admindashboard/index','AdminController@index');
					Route::post('admindashboard/index','MessageController@search');						
					Route::post('admindashboard/whitelist','WhiteListController@search');
				});								
				Route::resource('admindashboard','AdminController');	
				Route::resource('whitelist','WhiteListController');		
				Route::resource('course','CourseController');	
		});

		
							
		Route::group(['middleware' =>'admin'], function () {
			Route::resource('teacherdashboard','TeacherController');							
			Route::resource('teacherfile','TeacherFileController');			
		});
		Route::resource('teacherfile','TeacherFileController',['except' => ['store,create']]);					
		Route::resource('message','MessageController',['only' => ['destroy','show']]);					
	});				
});

app/Course.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
class Course extends Model
{
    use SoftDeletes;
    protected $dates = ['deleted_at'];	
	protected $table='courses';
    protected $fillable = [
        'name', 'description','imagepath'
    ];
}

app/Http/Controllers/CourseController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use Storage;
use App\Course;
use App\Http\Requests;
use App\Http\Requests\CourseRequest;
use App\Http\Controllers\Controller;

class CourseController extends Controller
{
	public function create(Request $request){
		$referer=$request->headers->get('referer');
		if(strpos($referer,'=')===false){
			$request->session()->put('referer',$referer);			    					
		}		
		return view('course.create');
	}
	public function store(CourseRequest $request){
	    $file=$request->file('file');
		$name=$request['name'];
		$extension=$file->getClientOriginalExtension();
		$filename=$name.'_'.rand(11111,99999).'.'.$extension;		
        $filecontents= file_get_contents($file->getRealPath());        
        $filepath='cms/courses/'.$filename;            
        Storage::disk('uploads')->put($filepath, $filecontents);

		$course=new Course;
		$course->name=strtoupper($request['name']);
		$course->description=$request['description'];
		$course->imagepath='uploads/'.$filepath;		
		$course->save();
		$request->session()->forget('referer');
		$request->session()->flash('status', 'Course added.');
		return redirect('admindashboard/courses');
	}
	public function edit(Request $request,$id){
		$course=Course::where('id','=',$id)->first();
		$referer=$request->headers->get('referer');
		if(strpos($referer,'=')===false){
			$request->session()->put('referer',$referer);			    					
		}		
		return view('course.edit')->with(compact('course'));		
	}
	public function update(CourseRequest $request,$id){
	    $file=$request->file('file');
		$name=$request['name'];
		$extension=$file->getClientOriginalExtension();
		$filename=$name.'_'.rand(11111,99999).'.'.$extension;		
        $filecontents= file_get_contents($file->getRealPath());        
        $filepath='cms/courses/'.$filename;            
        Storage::disk('uploads')->put($filepath, $filecontents);

		$course=Course::where('id','=',$id)->first();
		$course->name=strtoupper($request['name']);
		$course->description=$request['description'];
		$course->imagepath='uploads/'.$filepath;		
		$course->update();
		$request->session()->forget('referer');
		$request->session()->flash('status', 'Course updated.');
		return redirect('admindashboard/courses');
	}
	public function destroy($id){
		$course=Course::where('id','=',$id)->first();
		$course->delete();
		$request->session()->flash('status', 'Course deleted.');
		return redirect('admindashboard/courses');			
	}
}

resources/views/course/create.blade.php
@extends('templates.dashboard')
@section('content')
<div class="twelve columns course">
	<div class="row">
		<div class="ten columns offset-by-one">
			<form method="POST" id="frmcreate" action="{{route('course.store')}}" enctype="multipart/form-data">
				{{csrf_field()}}
				<label for="name">Name</label>
				<input id="name" name="name" type="text" value="{{old('name')}}">
				<p class="error">{{ $errors->first('name') }}</p>									
				<label for="description">Description</label>
				<textarea id="description" name="description">{{old('description')}}</textarea>
				<p class="error">{{ $errors->first('name') }}</p>	
				<label for="file">File</label>
				<input id="file" name="file" type="file" value="{{old('file')}}">		
				<p class="error">{{ $errors->first('file') }}</p>																									
				<button class="button-primary" type="submit"><i class="fa fa-cloud-upload fa-2x"></i></button>										
				<a class="anchorblue animsition-link" href="{{ session('referer') }}">Back</a>
			</form>
		</div>
	</div>
</div>
@endsection

resources/views/course/edit.blade.php
@extends('templates.dashboard')
@section('content')
<div class="twelve columns course">
	<div class="row">
		<div class="ten columns offset-by-one">
			<form method="POST" id="frmcreate" action="{{route('course.update',['id'=>$course['id']])}}" enctype="multipart/form-data">
				{{csrf_field()}}
		        <input name="_method" type="hidden" value="PATCH">							      			
				<label for="name">Name</label>
				<input id="name" name="name" type="text" value="{{$course['name']}}">
				<p class="error">{{ $errors->first('name') }}</p>									
				<label for="description">Description</label>
				<textarea id="description" name="description">{{$course['description']}}</textarea>
				<p class="error">{{ $errors->first('name') }}</p>													
				<button class="button-primary" type="submit"><i class="fa fa-cloud-upload fa-2x"></i></button>										
				<a class="anchorblue animsition-link" href="{{ session('referer') }}">Back</a>
			</form>
		</div>
	</div>
</div>
@endsection